name: File Audit

on: pull_request

jobs:
  file-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "
          done
